sudo: false

language: scala

scala:
   - 2.12.8

branches:
  only:
    - master

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2/cache
  - $HOME/.nvm

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

